# Generated by Django 4.2.3 on 2023-08-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rand_key',
            field=models.IntegerField(default=0, verbose_name='Ключ для верификации'),
        ),
    ]
